# Generated by Django 3.0.7 on 2020-06-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('enCartelera', models.BooleanField(verbose_name=True)),
                ('genero', models.CharField(max_length=500)),
                ('duración', models.CharField(max_length=500)),
                ('nacionalidad', models.CharField(max_length=500)),
            ],
        ),
    ]
