# Generated by Django 3.0.7 on 2020-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=500)),
                ('nombre', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
