# Generated by Django 3.0.7 on 2020-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0005_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('fecha', models.CharField(max_length=500)),
            ],
        ),
    ]
