# Generated by Django 3.0.7 on 2020-06-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0009_entrada_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Funcion'),
        ),
    ]
