# Generated by Django 3.0.7 on 2020-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0011_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='prodcutoDescripcion', max_length=2000),
            preserve_default=False,
        ),
    ]
