# Generated by Django 3.0.7 on 2020-06-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0013_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='sucursal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Sucursal'),
        ),
    ]
