# Generated by Django 3.0.7 on 2020-07-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0014_funcion_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Sucursal'),
        ),
    ]
