# Generated by Django 3.0.7 on 2020-07-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0016_auto_20200705_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='Sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Sala'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Pelicula'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Sucursal'),
        ),
    ]
