# Generated by Django 3.0.7 on 2020-07-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0018_auto_20200705_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='Sala',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='sucursal',
        ),
    ]
