# Generated by Django 3.0.7 on 2020-07-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0019_auto_20200705_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='hora',
        ),
    ]
