# Generated by Django 3.0.7 on 2020-07-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0022_auto_20200705_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='Hola', max_length=500)),
                ('hora', models.TimeField(default='Hola', max_length=500)),
                ('Sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Sala')),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Pelicula')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cplus.Sucursal')),
            ],
        ),
    ]
