# Generated by Django 3.0.7 on 2020-07-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0024_auto_20200705_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='sucursal',
        ),
    ]
