# Generated by Django 3.0.7 on 2020-07-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0025_remove_sala_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcion',
            old_name='Sala',
            new_name='sala',
        ),
    ]
