# Generated by Django 3.0.7 on 2020-07-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cplus', '0028_producto_vip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto_VIP',
            new_name='Productovip',
        ),
    ]
